library(datasets)
library(readr)
library(ggplot2)
library(dplyr)
library(caret)
library(corrplot)
library(corrgram)
library(e1071)
library(C50)
library(GGally)
library(shiny)
library(leaflet)
data(iris)
View(iris)
unique(iris$Species)
ggpairs(iris, mapping=ggplot2::aes(colour = Species))